

//  Input will be a json set and it perform CRUD


export const routes = [
    {
        featureName:"ItemGroup",
        featureType:"CRUD",
        entryType:"modal",
        path:"item_groups",
        apiPath:"item_groups",
        fields:[
            {
                name:"id",
                type:"string",
                identifier:true
            },
            {
                name:"name",
                type:"string",
                required:true,
            },
            {
                name:"alias",
                type:"string",
                required:false,
            },
            {
                name:"parentId",
                moduleName:"ItemGroup",
                type:"string"
            },
        ],
    },
    {
        featureName:"ItemCategory",
        featureType:"CRUD",
        entryType:"modal",
        path:"item_categories",
        apiPath:"item_categories",
        fields:[
            {
                name:"id",
                type:"string",
                identifier:true
            },
            {
                name:"name",
                type:"string",
                required:true,
            },
            {
                name:"alias",
                type:"string",
                required:false,
            },
            {
                name:"parentId",
                moduleName:"ItemGroup",
                type:"string"
            },
        ],
    },
    {
        featureName:"ItemUnit",
        featureType:"CRUD",
        entryType:"modal",
        path:"item_units",
        apiPath:"item_units",
        fields:[
            {
                name:"id",
                type:"string",
                identifier:true
            },
            {
                name:"name",
                type:"string",
                required:true,
            },
            {
                name:"alias",
                type:"string",
                required:false,
            },
            {
                name:"parentId",
                moduleName:"ItemGroup",
                type:"string"
            },
        ],
    }
]